### PR TITLE
Bind all events typeahead

### PR DESCRIPTION
**Pull request by powange**

### CODE REVIEW

**Comment by brunowego** [comment]
Please, merge it! :+1:

**Comment by Siyfion** [comment]
All done.

**Comment by brunowego** [comment]
Thanks @Siyfion :+1:

**Comment by Siyfion** [comment]
@brunowego sorry it took so bloody long to get it merged in! :hankey:

**Comment by brunowego** [comment]
rlx

**Comment by Siyfion** [comment]
@powange & @brunowego There is a serious issue with this code somewhere, I'm going to have to remove it and revert back to the older version.

**Comment by reneolivo** [comment]
Also, make sure to check this line:
`if(eventForUpdate.indexOf(event.type) > 0){`
I think you meant to use >= instead of >

**Pull request merged**
