### PR TITLE
Full library refactoring

### PR DESCRIPTION
**Pull request by hmil**
This PR adds tests and enhances overall code quality. With this change, future work to integrate new features and fix bug is going to be much easier and future regressions will be less likely to happen.

Here is an excerpt from the changelog:
```
- Built files are now wrapped in [UMD](https://github.com/umdjs/umd)
- Add unit tests, jshint and continuous integration
- Moved built files to `dist/` folder
- Values set directly to $scope.model are no longer validated against the suggestions.
- Remove ambiguous "suggestionKey" parameter
- moved options not related to tt to top level
```

The new code quality standard requires 100% unit test coverage and manual inspection is required to check that good assertions are being performed. The code must pass jshint linting as well.

**Bugs have been fixed, some undocumented features may not work anymore**, but it is the price to pay for enhanced maintainability and stability.

### CODE REVIEW

**Comment by Siyfion** [comment]
Wow! Fantastic work @hmil! Really impressive changes, as you're now a contributor, feel free to merge these under the new version when you're happy (I'll let you press the button). ;)

**Comment by hmil** [comment]
Thank you! Could you enable the build on [travis](https://travis-ci.org/) such that testing gets integrated with github?

**Comment by hmil** [comment]
@Siyfion ping ↑

**Comment by Siyfion** [comment]
Sorry @hmil, I was moving house this weekend, so it all got a little crazy.

**Comment by Siyfion** [comment]
Travis CI is now enabled, though I'm not sure if it will work on pre-existing PRs, so this may not get checked until after it has been merged...?

**Pull request merged**
