### PR TITLE
do not apply ff focus fix when dataset is a plain array

### LINKED ISSUE #71: Firefox focus bugfix breaks update in Chrome
The patch from #67 by CyborgMaster blocks some model updates in Chrome (Version 43.0.2357.130 (64-bit))
Example: I'm clicking to one of the suggestions in the dropdown
Expected outcome: Model to be updated based on the selected suggestion
Current behaviour: The change to the value will be reverted by this firefox fix line when called from NgModelController.$$parseAndValidate, so writeToModelIfNeeded at the end will not do anything, thinking the value stayed the same...

(If the solution is to only run the line for FFox, https://github.com/srfrnk/ng-device-detector might be useful here)

### LINKED ISSUE #72: Firefox focus fix causes form to be invalid
The fix made for the firefox workaround causes the field to be invalid as it can return 'undefined'.

When the page is initially loading the parse function is executed and the check 
```
if (fromView === element.typeahead('val')) return ngModel.$modelValue;
```
evaluates true and therefore returns $modelValue. The problem is that $modelValue can be undefined and returning undefined from a $parser signifies that the field is invalid.

### PR DESCRIPTION
**Pull request by phra**
this PR fixes #71 , #72 and #79

### CODE REVIEW

**Comment by phra** [comment]
tell me if i have to amend the commit and remove the .min.js.

**Comment by Siyfion** [comment]
@phra can you remove the minified code from the PR, I'll sort it out once it's in.

**Comment by phra** [comment]
sure, i'll do this later.

**Comment by phra** [comment]
done, you can merge!

**Comment by Siyfion** [comment]
All done.

**Pull request merged**
